//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18047
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.Model {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibraryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject1.Model.LibraryStrings", typeof(LibraryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AC.
        /// </summary>
        internal static string EstadoAcre {
            get {
                return ResourceManager.GetString("EstadoAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AL.
        /// </summary>
        internal static string EstadoAlagoas {
            get {
                return ResourceManager.GetString("EstadoAlagoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AP.
        /// </summary>
        internal static string EstadoAmapa {
            get {
                return ResourceManager.GetString("EstadoAmapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AM.
        /// </summary>
        internal static string EstadoAmazonas {
            get {
                return ResourceManager.GetString("EstadoAmazonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BA.
        /// </summary>
        internal static string EstadoBahia {
            get {
                return ResourceManager.GetString("EstadoBahia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CE.
        /// </summary>
        internal static string EstadoCeara {
            get {
                return ResourceManager.GetString("EstadoCeara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DF.
        /// </summary>
        internal static string EstadoDistritoFederal {
            get {
                return ResourceManager.GetString("EstadoDistritoFederal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ES.
        /// </summary>
        internal static string EstadoEspiritoSanto {
            get {
                return ResourceManager.GetString("EstadoEspiritoSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GO.
        /// </summary>
        internal static string EstadoGoias {
            get {
                return ResourceManager.GetString("EstadoGoias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MA.
        /// </summary>
        internal static string EstadoMaranhao {
            get {
                return ResourceManager.GetString("EstadoMaranhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MT.
        /// </summary>
        internal static string EstadoMatoGrosso {
            get {
                return ResourceManager.GetString("EstadoMatoGrosso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MS.
        /// </summary>
        internal static string EstadoMatoGrossoDoSul {
            get {
                return ResourceManager.GetString("EstadoMatoGrossoDoSul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MG.
        /// </summary>
        internal static string EstadoMinasGerais {
            get {
                return ResourceManager.GetString("EstadoMinasGerais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PA.
        /// </summary>
        internal static string EstadoPara {
            get {
                return ResourceManager.GetString("EstadoPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PB.
        /// </summary>
        internal static string EstadoParaiba {
            get {
                return ResourceManager.GetString("EstadoParaiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PR.
        /// </summary>
        internal static string EstadoParana {
            get {
                return ResourceManager.GetString("EstadoParana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PE.
        /// </summary>
        internal static string EstadoPernambuco {
            get {
                return ResourceManager.GetString("EstadoPernambuco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PI.
        /// </summary>
        internal static string EstadoPiaui {
            get {
                return ResourceManager.GetString("EstadoPiaui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RJ.
        /// </summary>
        internal static string EstadoRiodeJaneiro {
            get {
                return ResourceManager.GetString("EstadoRiodeJaneiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RN.
        /// </summary>
        internal static string EstadoRioGrandeDoNorte {
            get {
                return ResourceManager.GetString("EstadoRioGrandeDoNorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RS.
        /// </summary>
        internal static string EstadoRioGrandeDoSul {
            get {
                return ResourceManager.GetString("EstadoRioGrandeDoSul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RO.
        /// </summary>
        internal static string EstadoRondonia {
            get {
                return ResourceManager.GetString("EstadoRondonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RR.
        /// </summary>
        internal static string EstadoRoraima {
            get {
                return ResourceManager.GetString("EstadoRoraima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SC.
        /// </summary>
        internal static string EstadoSantaCatarina {
            get {
                return ResourceManager.GetString("EstadoSantaCatarina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SP.
        /// </summary>
        internal static string EstadoSaoPaulo {
            get {
                return ResourceManager.GetString("EstadoSaoPaulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SE.
        /// </summary>
        internal static string EstadoSergipe {
            get {
                return ResourceManager.GetString("EstadoSergipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TO.
        /// </summary>
        internal static string EstadoTocantins {
            get {
                return ResourceManager.GetString("EstadoTocantins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ALM.
        /// </summary>
        internal static string LogradouroAlameda {
            get {
                return ResourceManager.GetString("LogradouroAlameda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AVN.
        /// </summary>
        internal static string LogradouroAvenida {
            get {
                return ResourceManager.GetString("LogradouroAvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BEC.
        /// </summary>
        internal static string LogradouroBeco {
            get {
                return ResourceManager.GetString("LogradouroBeco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BLV.
        /// </summary>
        internal static string LogradouroBoulevard {
            get {
                return ResourceManager.GetString("LogradouroBoulevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAS.
        /// </summary>
        internal static string LogradouroCais {
            get {
                return ResourceManager.GetString("LogradouroCais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAM.
        /// </summary>
        internal static string LogradouroCaminho {
            get {
                return ResourceManager.GetString("LogradouroCaminho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CMP.
        /// </summary>
        internal static string LogradouroCampo {
            get {
                return ResourceManager.GetString("LogradouroCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ESC.
        /// </summary>
        internal static string LogradouroEscada {
            get {
                return ResourceManager.GetString("LogradouroEscada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ETR.
        /// </summary>
        internal static string LogradouroEstrada {
            get {
                return ResourceManager.GetString("LogradouroEstrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FAV.
        /// </summary>
        internal static string LogradouroFavela {
            get {
                return ResourceManager.GetString("LogradouroFavela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FAZ.
        /// </summary>
        internal static string LogradouroFazenda {
            get {
                return ResourceManager.GetString("LogradouroFazenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FLT.
        /// </summary>
        internal static string LogradouroFloresta {
            get {
                return ResourceManager.GetString("LogradouroFloresta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ILH.
        /// </summary>
        internal static string LogradouroIlha {
            get {
                return ResourceManager.GetString("LogradouroIlha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JRD.
        /// </summary>
        internal static string LogradouroJardim {
            get {
                return ResourceManager.GetString("LogradouroJardim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LAD.
        /// </summary>
        internal static string LogradouroLadeira {
            get {
                return ResourceManager.GetString("LogradouroLadeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LRG.
        /// </summary>
        internal static string LogradouroLargo {
            get {
                return ResourceManager.GetString("LogradouroLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LTM.
        /// </summary>
        internal static string LogradouroLoteamento {
            get {
                return ResourceManager.GetString("LogradouroLoteamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LUG.
        /// </summary>
        internal static string LogradouroLugar {
            get {
                return ResourceManager.GetString("LogradouroLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MRR.
        /// </summary>
        internal static string LogradouroMorro {
            get {
                return ResourceManager.GetString("LogradouroMorro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PQE.
        /// </summary>
        internal static string LogradouroParque {
            get {
                return ResourceManager.GetString("LogradouroParque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PAS.
        /// </summary>
        internal static string LogradouroPasseio {
            get {
                return ResourceManager.GetString("LogradouroPasseio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRC.
        /// </summary>
        internal static string LogradouroPraca {
            get {
                return ResourceManager.GetString("LogradouroPraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRA.
        /// </summary>
        internal static string LogradouroPraia {
            get {
                return ResourceManager.GetString("LogradouroPraia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a REC.
        /// </summary>
        internal static string LogradouroRecanto {
            get {
                return ResourceManager.GetString("LogradouroRecanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ROD.
        /// </summary>
        internal static string LogradouroRodovia {
            get {
                return ResourceManager.GetString("LogradouroRodovia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RUA.
        /// </summary>
        internal static string LogradouroRua {
            get {
                return ResourceManager.GetString("LogradouroRua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SRV.
        /// </summary>
        internal static string LogradouroServidao {
            get {
                return ResourceManager.GetString("LogradouroServidao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRV.
        /// </summary>
        internal static string LogradouroTravessa {
            get {
                return ResourceManager.GetString("LogradouroTravessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VIA.
        /// </summary>
        internal static string LogradouroVia {
            get {
                return ResourceManager.GetString("LogradouroVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VIL.
        /// </summary>
        internal static string LogradouroVila {
            get {
                return ResourceManager.GetString("LogradouroVila", resourceCulture);
            }
        }
    }
}
